### EASY
GET http://LOCALHOST:8080/hello HTTP/2
Accept: application/json, text/plain
Cache-Control: no-cache
Accept-Encoding: gzip
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb25vIiwiaWF0IjoxNzYxNzQ2NjYxLCJleHAiOjE3NjE3NDc1NjEsInR5cGUiOiJhY2Nlc3MiLCJyb2xlcyI6WyJST0xFX1VTRVIiXX0.YqfFElLBmGMGoMd4Q0i7Ds4WA_cRB7giLL5QLocCbVU

### Actuator :: info
GET http://LOCALHOST:8080/actuator/info HTTP/2
Accept: application/json
Cache-Control: no-cache
Accept-Encoding: gzip
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb25vIiwiaWF0IjoxNzYxNzQ2NjYxLCJleHAiOjE3NjE3NDc1NjEsInR5cGUiOiJhY2Nlc3MiLCJyb2xlcyI6WyJST0xFX1VTRVIiXX0.YqfFElLBmGMGoMd4Q0i7Ds4WA_cRB7giLL5QLocCbVU

### Actuator :: health
GET http://LOCALHOST:8080/actuator/health HTTP/2
Accept: application/json
Cache-Control: no-cache
Accept-Encoding: gzip
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb25vIiwiaWF0IjoxNzYxNzQ2NjYxLCJleHAiOjE3NjE3NDc1NjEsInR5cGUiOiJhY2Nlc3MiLCJyb2xlcyI6WyJST0xFX1VTRVIiXX0.YqfFElLBmGMGoMd4Q0i7Ds4WA_cRB7giLL5QLocCbVU

### Actuator :: ratelimiters
GET http://LOCALHOST:8080/actuator/ratelimiters HTTP/2
Accept: application/json
Cache-Control: no-cache
Accept-Encoding: gzip
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb25vIiwiaWF0IjoxNzYxNzQ2NjYxLCJleHAiOjE3NjE3NDc1NjEsInR5cGUiOiJhY2Nlc3MiLCJyb2xlcyI6WyJST0xFX1VTRVIiXX0.YqfFElLBmGMGoMd4Q0i7Ds4WA_cRB7giLL5QLocCbVU

### Actuator :: startup
GET http://LOCALHOST:8080/actuator/startup HTTP/2
Accept: application/json
Cache-Control: no-cache
Accept-Encoding: gzip
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb25vIiwiaWF0IjoxNzYxNzQ2NjYxLCJleHAiOjE3NjE3NDc1NjEsInR5cGUiOiJhY2Nlc3MiLCJyb2xlcyI6WyJST0xFX1VTRVIiXX0.YqfFElLBmGMGoMd4Q0i7Ds4WA_cRB7giLL5QLocCbVU

### Actuator :: metrics
GET http://LOCALHOST:8080/actuator/metrics/client.service.findAll2.timing
Accept: application/json
Cache-Control: no-cache
Accept-Encoding: gzip
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb25vIiwiaWF0IjoxNzYxNzQ2NjYxLCJleHAiOjE3NjE3NDc1NjEsInR5cGUiOiJhY2Nlc3MiLCJyb2xlcyI6WyJST0xFX1VTRVIiXX0.YqfFElLBmGMGoMd4Q0i7Ds4WA_cRB7giLL5QLocCbVU

### Client :: findAll
GET http://LOCALHOST:8080/client?page=0&size=10 HTTP/2
Accept: application/json
Cache-Control: no-cache
Accept-Encoding: gzip
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb25vIiwiaWF0IjoxNzYxNzQ2NjYxLCJleHAiOjE3NjE3NDc1NjEsInR5cGUiOiJhY2Nlc3MiLCJyb2xlcyI6WyJST0xFX1VTRVIiXX0.YqfFElLBmGMGoMd4Q0i7Ds4WA_cRB7giLL5QLocCbVU

### Client :: findByAccountNo
GET http://LOCALHOST:8080/client/ABC001 HTTP/2
Accept: application/json
Cache-Control: no-cache
Accept-Encoding: gzip
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb25vIiwiaWF0IjoxNzYxNzQ2NjYxLCJleHAiOjE3NjE3NDc1NjEsInR5cGUiOiJhY2Nlc3MiLCJyb2xlcyI6WyJST0xFX1VTRVIiXX0.YqfFElLBmGMGoMd4Q0i7Ds4WA_cRB7giLL5QLocCbVU

### Client :: doSomeWork
GET http://LOCALHOST:8080/client/doSomeWork HTTP/2
Accept: application/json
Cache-Control: no-cache
Accept-Encoding: gzip
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb25vIiwiaWF0IjoxNzYxNzQ2NjYxLCJleHAiOjE3NjE3NDc1NjEsInR5cGUiOiJhY2Nlc3MiLCJyb2xlcyI6WyJST0xFX1VTRVIiXX0.YqfFElLBmGMGoMd4Q0i7Ds4WA_cRB7giLL5QLocCbVU

### Client :: save
POST http://LOCALHOST:8080/client HTTP/2
content-type: application/json
Cache-Control: no-cache
Accept-Encoding: gzip

{
}

### ClientStatus :: active
GET http://LOCALHOST:8080/public/clientStatus/active HTTP/2
Accept: application/json
Cache-Control: no-cache
Accept-Encoding: gzip

### ClientStatus :: all
GET http://LOCALHOST:8080/public/clientStatus/all HTTP/2
Accept: application/json
Cache-Control: no-cache
Accept-Encoding: gzip

### Messaging :: test send
GET http://LOCALHOST:8080/messaging/client/1 HTTP/2
Accept: application/json
Cache-Control: no-cache
Accept-Encoding: gzip
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb25vIiwiaWF0IjoxNzYxNzQ2NjYxLCJleHAiOjE3NjE3NDc1NjEsInR5cGUiOiJhY2Nlc3MiLCJyb2xlcyI6WyJST0xFX1VTRVIiXX0.YqfFElLBmGMGoMd4Q0i7Ds4WA_cRB7giLL5QLocCbVU
