spring:

  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      validation-timeout: 10000
      maximum-pool-size: 10

  graphql:
    graphiql:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true

#logging:
#  level:
#    org.springframework.context.annotation: TRACE
#    org.springframework.web.socket: DEBUG
#    org.apache.activemq: DEBUG
#    org.springframework.jms: DEBUG
